---
title: EHI Website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: The website of the Event Horizon Imager project, and associated initiatives.
url: https://event-horizon-imager.github.io/EHI-Website.github.io/
